# -*- coding: utf-8 -*-
"""Main_fow(Data_science)[task-3].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-33v0KdDANI79eZJ-NEAtvc-pdEQn276
"""

!pip install ydata-profiling

#EDA

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Main_flow(Data science)/USvideos.csv')

data.head()

data.info()

data.isnull().sum()

data.describe()

data.shape

data_int = data.dtypes[data.dtypes == 'int64'].index

data_int

data_int = data[data_int]

data_int.hist(figsize=(10, 6))
plt.tight_layout()
plt.show()

# KDE plots
sns.kdeplot(data=data_int, fill=True, common_norm=False, palette="crest", alpha=.5, linewidth=0)
plt.tight_layout()
plt.show()

sns.boxplot(data=data_int, palette="Set2")
plt.tight_layout()
plt.show()

corr = data_int.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

import ydata_profiling

ydata_profiling.ProfileReport(data)

