# -*- coding: utf-8 -*-
"""Main_flow(Data_science)[task-2].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FM-K8_kVmfQzS7cFK0pGMyJGSgHExsCC
"""

!pip install ydata-profiling

import pandas as pd
import numpy as np
from sklearn.preprocessing import *
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Main_flow(Data science)/01.Data Cleaning and Preprocessing.csv")

display(data)

data.columns

data.dtypes

data.describe()

data.isnull().sum()

data.shape

data[[ 'ChipRate','ChipLevel4 ', 'T-upperExt-2 ', 'T-lowerExt-2  ',
       'WhiteFlow-4 ', 'AA-Wood-4  ', 'ChipMoisture-4 ',
       'SteamFlow-4 ', 'Lower-HeatT-3', 'Upper-HeatT-3 ', 'ChipMass-4 ',
       'WeakLiquorF ', 'BlackFlow-2 ', 'WeakWashF ', 'SteamHeatF-3 ',
       'T-Top-Chips-4 ']].fillna(method='backfill',inplace =True)

data.columns





"BF-CMratio","'BlowFlow'",'ChipLevel4 ','T-upperExt-2 ','T-lowerExt-2  ','UCZAA','ChipMass-4 ','WeakLiquorF '

for i in data.columns:
  if data[i].dtype == "float64":
    data[i].plot(kind='box')
    plt.show()

plt.show()

Profile = ProfileReport(data)
Profile

