# -*- coding: utf-8 -*-
"""Main_flow(Data_science)[task-2].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FM-K8_kVmfQzS7cFK0pGMyJGSgHExsCC
"""

!pip install ydata-profiling

import pandas as pd
import numpy as np
from sklearn.preprocessing import *
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

pd.options.mode.copy_on_write = True



data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Main_flow(Data science)/01.Data Cleaning and Preprocessing.csv")

display(data)

data.columns

data.dtypes

data.describe()

data.isnull().sum()

data.shape

data.fillna(method='bfill',inplace = True)

data.columns



data.isnull().sum()



"BF-CMratio","'BlowFlow'",'ChipLevel4 ','T-upperExt-2 ','T-lowerExt-2  ','UCZAA','ChipMass-4 ','WeakLiquorF '



for i in data.columns:
  if data[i].dtype == "float64":
    data[i].plot(kind='box')
    plt.show()

plt.show()

data_non_corr = data.drop(['Observation','BlackFlow-2 ' ,'UCZAA','Upper-HeatT-3 ' ,'WhiteFlow-4 '] , axis= 1)

data_non_corr.columns

import numpy as np
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p, validate=True)
transformer.transform(data_non_corr)

Profile = ProfileReport(data)
Profile

Profile = ProfileReport(data_non_corr)
Profile

